package stock;

import java.awt.Graphics2D;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static stock.Master.EditProduct;
import static stock.StockData.connection;

public class EditProduct extends javax.swing.JFrame {

    File pic = null;

    public EditProduct() {
        initComponents();
        cmbItemSelect.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel4 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbItemSelect = new javax.swing.JComboBox();
        pnlEP = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUpdateName = new java.awt.TextField();
        spnUpdateStock = new javax.swing.JSpinner();
        txtUpdatePrice = new java.awt.TextField();
        lblPic = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Product");
        setExtendedState(6);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlMain.setBackground(new java.awt.Color(153, 153, 153));
        pnlMain.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setText("Item Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 140, 0, 0);
        pnlMain.add(jLabel1, gridBagConstraints);

        cmbItemSelect.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        cmbItemSelect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        cmbItemSelect.setLightWeightPopupEnabled(false);
        cmbItemSelect.setEditable(true);
        cmbItemSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemSelectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 0, 0);
        pnlMain.add(cmbItemSelect, gridBagConstraints);

        pnlEP.setBackground(new java.awt.Color(204, 204, 204));
        pnlEP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel11.setText("Stock ");
        pnlEP.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 70, 30));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel2.setText("Price");
        pnlEP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel5.setText("Name");
        pnlEP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, 30));

        txtUpdateName.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        txtUpdateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateNameActionPerformed(evt);
            }
        });
        pnlEP.add(txtUpdateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, 40));

        spnUpdateStock.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        spnUpdateStock.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnUpdateStock.setToolTipText("Extra Stock to add");
        pnlEP.add(spnUpdateStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 60, 40));

        txtUpdatePrice.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        txtUpdatePrice.setName(""); // NOI18N
        txtUpdatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdatePriceActionPerformed(evt);
            }
        });
        pnlEP.add(txtUpdatePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 80, 40));

        lblPic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEP.add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 210, 150));

        btnBrowse.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnBrowse.setText("Select Image");
        btnBrowse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBrowse.setBorderPainted(false);
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        pnlEP.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 140, 0, 0);
        pnlMain.add(pnlEP, gridBagConstraints);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/Resources/magnifier12.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -17;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 0, 130);
        pnlMain.add(btnSearch, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel9.setText("Edit Details ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 140, 0, 0);
        pnlMain.add(jLabel9, gridBagConstraints);

        btnUpdate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnUpdate.setText("Update ");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 55, 0);
        pnlMain.add(btnUpdate, gridBagConstraints);

        btnDeleteProduct.setBackground(new java.awt.Color(255, 204, 204));
        btnDeleteProduct.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnDeleteProduct.setText("Delete Item ");
        btnDeleteProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteProduct.setBorderPainted(false);
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 55, 0);
        pnlMain.add(btnDeleteProduct, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 90, 9, 131);
        getContentPane().add(pnlMain, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        AddImage();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtUpdateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateNameActionPerformed

    private void txtUpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdatePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdatePriceActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null,
                "Are you surce you want to delete " + txtUpdateName.getText() + " ?", "Confirmation ", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
            String keyName = StockData.getName(EditProduct());
            new StockData().DeleteProduct(EditProduct(), keyName);
            Master.UpdateCombobox(cmbItemSelect);
            this.setVisible(false);
            txtUpdateName.setText(null);
            txtUpdatePrice.setText(null);
            spnUpdateStock.setValue(0);
            lblPic.setIcon(null);
            this.setVisible(true);
        }


    }//GEN-LAST:event_btnDeleteProductActionPerformed

    public boolean yes(boolean x) {
        return x;
    }
    private void cmbItemSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItemSelectActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProduct().setVisible(true);
            }
        });
    }

    public File AddImage() {

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("jpeg", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {

            File selectedFile = file.getSelectedFile();
            pic = selectedFile;
            String path = selectedFile.getAbsolutePath();
            lblPic.setIcon(ResizeImage(path));

        }
        return pic;
    }

    public ImageIcon ResizeImage(String imagePath) {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblPic.getWidth(), lblPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;

    }

    public void UpdateProduct(String keyStr, String name, double price, int quantity) throws FileNotFoundException {
        int key = Integer.parseInt(keyStr);
        Icon lblicon = lblPic.getIcon();

        int w = lblicon.getIconWidth();
        int h = lblicon.getIconHeight();
        GraphicsEnvironment ge
                = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        GraphicsConfiguration gc = gd.getDefaultConfiguration();
        BufferedImage bi = gc.createCompatibleImage(w, h);
        Graphics2D g = bi.createGraphics();
        lblicon.paintIcon(null, g, 0, 0);
        g.dispose();

        File outputPic = new File("image.jpg");
        try {
            ImageIO.write(bi, "jpg", outputPic);
        } catch (IOException ex) {
            Logger.getLogger(EditProduct.class.getName()).log(Level.SEVERE, null, ex);
        }

        FileInputStream fis = null;

        if (outputPic != null) {
            fis = new FileInputStream(outputPic);
        }
        try {
//            StockData.stmt.execute("INSERT INTO PRODUCTS(NAME, PRICE, QUANTITY, IMAGE) VALUES('" + name + "', " + price + "," + quantity + "," + fis + ")");
            PreparedStatement statement = connection.prepareStatement("UPDATE PRODUCTS SET NAME=?, PRICE=?, QUANTITY=?, IMAGE=? WHERE PRODUCTID = " + key);
            statement.setString(1, name);
            statement.setDouble(2, price);
            statement.setInt(3, quantity);
            if (fis != null) {
                statement.setBlob(4, fis);
            } else {
                statement.setNull(4, java.sql.Types.BLOB);
            }

            statement.execute();

        } catch (SQLException ex) {
            Logger.getLogger(StockData.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon icon = new ImageIcon(getClass().getResource("/stock/Resources/tick.png"));
        JOptionPane.showMessageDialog(btnUpdate,
                name + " has been updated successfully.", "Confirmation", JOptionPane.INFORMATION_MESSAGE, icon);
    }

//    public void Close(){
//   this.dispose();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBrowse;
    public javax.swing.JButton btnDeleteProduct;
    public javax.swing.JButton btnSearch;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JComboBox cmbItemSelect;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblPic;
    public javax.swing.JPanel pnlEP;
    public javax.swing.JPanel pnlMain;
    public javax.swing.JSpinner spnUpdateStock;
    public java.awt.TextField txtUpdateName;
    public java.awt.TextField txtUpdatePrice;
    // End of variables declaration//GEN-END:variables
}
