/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static stock.StockData.connection;
import static stock.StockData.stmt;

/**
 *
 * @author st8511x
 */
public class ManageAccounts extends javax.swing.JFrame {

    LoginTopLevel loginTop = new LoginTopLevel();
    String welcome = Master.w;

    /**
     * Creates new form ManageEmployeeAccess
     */
    public ManageAccounts() {
        initComponents();
        txtWelcome.setText(Master.w);
        txtWelcome.setText(welcome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ShStockDBPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ShStockDBPU").createEntityManager();
        accountsQuery = java.beans.Beans.isDesignTime() ? null : ShStockDBPUEntityManager.createQuery("SELECT a FROM Accounts a");
        accountsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : accountsQuery.getResultList();
        pnlAddUser = new javax.swing.JPanel();
        btnAddUser = new javax.swing.JButton();
        txtUserIDSignUp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        radioMngUsers = new javax.swing.JRadioButton();
        txtNewPassAgain = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtWelcome = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtUsernameEdit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnSaveChanges = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        radioPrivileges = new javax.swing.JCheckBox();
        radioEmployee = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Employee Accounts");
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAddUser.setBackground(new java.awt.Color(255, 204, 153));
        pnlAddUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddUser.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddUser.setBorderPainted(false);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        pnlAddUser.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, -1));

        txtUserIDSignUp.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        pnlAddUser.add(txtUserIDSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 130, 30));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel11.setText("Password");
        pnlAddUser.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, 30));

        radioMngUsers.setBackground(new java.awt.Color(255, 204, 153));
        radioMngUsers.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        radioMngUsers.setText("Manage Users");
        pnlAddUser.add(radioMngUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 180, -1));

        txtNewPassAgain.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        pnlAddUser.add(txtNewPassAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 130, 30));

        txtNewPass.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        pnlAddUser.add(txtNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 130, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setText("Re-enter Password");
        pnlAddUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 190, 30));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel16.setText("Name");
        pnlAddUser.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 80, 20));

        txtName.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlAddUser.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 130, 30));

        jLabel10.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel10.setText("Check if they have privileges");
        pnlAddUser.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setText("Username");
        pnlAddUser.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, 20));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel1.setText("Fill in the details below to grant an employee access to stock ");
        pnlAddUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 20));

        getContentPane().add(pnlAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 460, 270));

        txtWelcome.setEditable(false);
        txtWelcome.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        txtWelcome.setBorder(null);
        txtWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWelcomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel12.setText("Welcome");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 100, 40));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel13.setText("Exisiting Users");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 160, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsernameEdit.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jPanel1.add(txtUsernameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 30));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel17.setText("Username");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 20));

        btnSaveChanges.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaveChanges.setBorderPainted(false);
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, -1));

        btnDeleteUser.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteUser.setBorderPainted(false);
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel14.setText("Privileges?");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel15.setText("Empoyee?");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        radioPrivileges.setBackground(new java.awt.Color(204, 204, 255));
        radioPrivileges.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        radioPrivileges.setText("Manage Accounts");
        jPanel1.add(radioPrivileges, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        radioEmployee.setBackground(new java.awt.Color(204, 204, 255));
        radioEmployee.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        radioEmployee.setText("Update Stock");
        radioEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(radioEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 340, 200));

        jLabel4.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel4.setText("View all users (customers and employees below)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 370, 30));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel18.setText("Edit Account");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 160, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, accountsList, table);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userid}"));
        columnBinding.setColumnName("Userid");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${username}"));
        columnBinding.setColumnName("Username");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${password}"));
        columnBinding.setColumnName("Password");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${employee}"));
        columnBinding.setColumnName("Employee");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${manageaccounts}"));
        columnBinding.setColumnName("Manageaccounts");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${image}"));
        columnBinding.setColumnName("Image");
        columnBinding.setColumnClass(java.io.Serializable.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(table);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 780, 260));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel19.setText("Add Employee");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 160, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 780, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 340, 20));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:

        int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete " + txtUsernameEdit.getText() + " ?", "Confirmation ", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
            StockData.DeleteUser(txtUsernameEdit.getText());
            this.dispose();
            txtUsernameEdit.setText(null);
            radioPrivileges.setSelected(false);
            radioEmployee.setSelected(false);
            main(new String[]{});//refreshes form with new data
            txtWelcome.setText(welcome);
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
// TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to make these changes?", "Confirmation ", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
            boolean privileges, stock;
            stock = radioEmployee.isSelected();
            privileges = radioPrivileges.isSelected();
            String username = txtUsernameEdit.getText();
            StockData.UpdateAccount(stock, privileges, username);
            this.dispose();
            txtUsernameEdit.setText(null);
            radioEmployee.setSelected(false);
            radioPrivileges.setSelected(false);
            main(new String[]{});//refreshes form with new data
            ((DefaultTableModel) table.getModel()).fireTableDataChanged();
            txtWelcome.setText(welcome);

        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed

        try {
            //AddAccount(String name, String Password, boolean Employee, boolean ManageAcounts, Image image) throws FileNotFoundException {
            String name = txtName.getText();
            String userName = txtUserIDSignUp.getText();
            StockData stockData = new StockData();
            boolean usernameTaken = stockData.CheckUsernameSignUP(userName);
            //account can only be added if username is unique
            if (usernameTaken == false) {
                char[] pass = txtNewPass.getPassword();
                String strPass = new String(pass);
                char[] passReenter = txtNewPassAgain.getPassword();
                String passReenterStr = new String(passReenter);
                //MANAGE ACCOUNTS AUTHORISATION
                boolean privileges = radioMngUsers.isSelected();
                if (strPass.equals(passReenterStr)) {
                    try {
                        //find code to ensure that the the userID has not been taken up already
                        stockData.AddAccount(name, userName, strPass, true, privileges, null);
                        this.dispose();
                        txtName.setText(null);
                        txtNewPass.setText(null);
                        txtNewPassAgain.setText(null);
                        txtUserIDSignUp.setText(null);
                        radioMngUsers.setSelected(false);
                        main(new String[]{});
                        txtWelcome.setText(welcome);
                    } catch (SQLException ex) {
                        Logger.getLogger(Master.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(ManageAccounts.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(new JButton(),
                            "Please reenter passwords", "Passwords Mismatch", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageAccounts.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddUserActionPerformed

    private void txtWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWelcomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWelcomeActionPerformed

    private void radioEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ShStockDBPUEntityManager;
    private java.util.List<stock.Accounts> accountsList;
    private javax.persistence.Query accountsQuery;
    public javax.swing.JButton btnAddUser;
    public javax.swing.JButton btnDeleteUser;
    public javax.swing.JButton btnSaveChanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JPanel pnlAddUser;
    public javax.swing.JCheckBox radioEmployee;
    public javax.swing.JRadioButton radioMngUsers;
    public javax.swing.JCheckBox radioPrivileges;
    public javax.swing.JTable table;
    public javax.swing.JTextField txtName;
    public javax.swing.JPasswordField txtNewPass;
    public javax.swing.JPasswordField txtNewPassAgain;
    public javax.swing.JTextField txtUserIDSignUp;
    public javax.swing.JTextField txtUsernameEdit;
    public javax.swing.JTextField txtWelcome;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
